version: '2'
services:
  backend:
    container_name: demo
    build:
      dockerfile: Dockerfile
    image: demo:latest
    ports:
      - 8082:8080
    networks:
      - spring-cloud-network
  frontend:
    image: demo-ui
    container_name: demo-ui
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 8081:80
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/basics?allowPublicKeyRetrieval=true&useSSL=false
    depends_on:
      - backend
    networks:
      - spring-cloud-network
  mysqldb:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: basics
      MYSQL_USER: test
      MYSQL_PASSWORD: test1234
      MYSQL_ROOT_PASSWORD: test1234
    networks:
      - spring-cloud-network
networks:
  spring-cloud-network:
    driver: bridge

